FROM quay.io/fedora/fedora-coreos:stable

COPY autoupdate.service /etc/systemd/system/autoupdate.service
COPY autoupdate.timer /etc/systemd/system/autoupdate.timer
COPY mnt-media.mount /etc/systemd/system/mnt-media.mount

COPY containers/nextcloud/nextcloud-kube.yaml /etc/containers/systemd/1001/nextcloud-kube.yaml
COPY containers/nextcloud/nextcloud-kube.kube /etc/containers/systemd/1001/nextcloud-kube.kube

RUN rpm-ostree install \
      cockpit \
      cockpit-podman \
      cockpit-selinux \
      cockpit-networkmanager \
      btop

RUN ostree container commit
