FROM quay.io/fedora/fedora-coreos:stable

COPY autoupdate.service /etc/systemd/system/autoupdate.service

RUN rpm-ostree install \
      cockpit \
      cockpit-podman \
      cockpit-selinux \
      cockpit-networkmanager

RUN ostree container commit
