name: build-fcos

on:
  # schedule:
  #   - cron: 0 1 * * MON

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-coreos-image:
    name: build-coreos-image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate date tag
        id: generate-tags
        shell: bash
        run: |
          BUILD_DATE=$(date --iso-8601)
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: fcos-image
          file: fcos-image/Containerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.generate-tags.outputs.BUILD_DATE }},${{ env.IMAGE_NAME }}:latest
